name: cd

on:
  workflow_run:
    workflows: [ci]
    types:
      - completed

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      
      - name: Set permissions for private key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Pull Docker image
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-118-107-108.us-east-2.compute.amazonaws.com 'sudo docker pull ${{ env.DOCKER_USERNAME }}/slack-bot:${{ github.sha }}'

      - name: Stop running container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-118-107-108.us-east-2.compute.amazonaws.com 'sudo docker stop cddemo || true'
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-118-107-108.us-east-2.compute.amazonaws.com 'sudo docker rm cddemo || true'

      - name: Run new container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-118-107-108.us-east-2.compute.amazonaws.com 'sudo docker run -d --name slack-bot -p 80:5000 ${{ env.DOCKER_USERNAME }}/slack-bot:${{ github.sha }}'
